package by.shaaldy.bot.dialog;

public enum DialogState {
  IDLE,
  AWAITING_LINK,
  AWAITING_TAGS,
  AWAITING_FILTERS,
  AWAITING_UNTRACK,
  AWAITING_TAG_LINK,
  AWAITING_TAG_ACTION,
  AWAITING_TAG_NAME
}
