spring.application.name=bot
server.port=8080

# Telegram (токен только из переменной окружения, в репозиторий не коммитим)
app.telegram-token=${TELEGRAM_TOKEN}

# Адрес scrapper для HTTP-вызовов bot -> scrapper
app.scrapper-base-url=http://localhost:8081

# --- Транспорт уведомлений (требование ДЗ: message-transport=Kafka|HTTP) ---
app.message-transport=HTTP

# --- Kafka: имена топиков в конфиге, должны совпадать со scrapper ---
app.kafka.topics.updates=link-updates
app.kafka.topics.updates-dlq=link-updates-dlq

app.cache.enabled=false
app.cache.list-ttl=PT5M
app.digest.zone=Europe/Moscow

# Логирование
logging.file.name=logs/bot.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.clean-history-on-start=true






spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=bot-updates
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=by.shaaldy.bot.dto.bot

# --- Redis: кэш /list ---
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
